//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMessagingApiClient.MessageDisposedServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="address", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageDisposedServiceReference.addresstype TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageDisposedServiceReference.addresstype Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="addresstype", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    public enum addresstype : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dispositionType", Namespace="http://api.relayhealth.com/2012/06/messaging/types")]
    public enum dispositionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Displayed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dispatched = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Denied = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.entitynotfoundfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.accessdeniedfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.invalidinputfault))]
    public partial class fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class entitynotfoundfault : SecureMessagingApiClient.MessageDisposedServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class accessdeniedfault : SecureMessagingApiClient.MessageDisposedServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidinputfault : SecureMessagingApiClient.MessageDisposedServiceReference.fault {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.relayhealth.com/2012/06/messaging", ConfigurationName="MessageDisposedServiceReference.messageDisposed")]
    public interface messageDisposed {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/post", ReplyAction="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postInvalidInputFaul" +
            "tFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postEntityNotFoundFa" +
            "ultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postAccessDeniedFaul" +
            "tFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageDisposedServiceReference.fault), Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        bool post(System.Guid messageId, SecureMessagingApiClient.MessageDisposedServiceReference.address recipient, SecureMessagingApiClient.MessageDisposedServiceReference.dispositionType dispositionType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface messageDisposedChannel : SecureMessagingApiClient.MessageDisposedServiceReference.messageDisposed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class messageDisposedClient : System.ServiceModel.ClientBase<SecureMessagingApiClient.MessageDisposedServiceReference.messageDisposed>, SecureMessagingApiClient.MessageDisposedServiceReference.messageDisposed {
        
        public messageDisposedClient() {
        }
        
        public messageDisposedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public messageDisposedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageDisposedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageDisposedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool post(System.Guid messageId, SecureMessagingApiClient.MessageDisposedServiceReference.address recipient, SecureMessagingApiClient.MessageDisposedServiceReference.dispositionType dispositionType) {
            return base.Channel.post(messageId, recipient, dispositionType);
        }
    }
}
