<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="messageDisposed" targetNamespace="http://api.relayhealth.com/2012/06/messaging" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://api.relayhealth.com/2012/06/messaging" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsp:Policy wsu:Id="soap11_policy">
        <wsp:ExactlyOne>
            <wsp:All>
                <wsoma:OptimizedMimeSerialization xmlns:wsoma="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"/>
                <sp:TransportBinding xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
                    <wsp:Policy>
                        <sp:TransportToken>
                            <wsp:Policy>
                                <sp:HttpsToken RequireClientCertificate="true"/>
                            </wsp:Policy>
                        </sp:TransportToken>
                        <sp:AlgorithmSuite>
                            <wsp:Policy>
                                <sp:Basic256/>
                            </wsp:Policy>
                        </sp:AlgorithmSuite>
                        <sp:Layout>
                            <wsp:Policy>
                                <sp:Strict/>
                            </wsp:Policy>
                        </sp:Layout>
                    </wsp:Policy>
                </sp:TransportBinding>
                <wsaw:UsingAddressing/>
            </wsp:All>
        </wsp:ExactlyOne>
    </wsp:Policy>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://api.relayhealth.com/2012/06/messaging">
            <xsd:element name="post">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="messageId" type="q1:guid" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/"/>
                        <xsd:element minOccurs="0" name="recipient" nillable="true" type="q2:address" xmlns:q2="http://api.relayhealth.com/2012/05/messaging/types"/>
                        <xsd:element minOccurs="0" name="dispositionType" type="q3:dispositionType" xmlns:q3="http://api.relayhealth.com/2012/06/messaging/types"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="postResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" name="postResult" type="xsd:boolean"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
        <xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://api.relayhealth.com/2012/05/messaging/types" xmlns:tns="http://api.relayhealth.com/2012/05/messaging/types">
            <xsd:complexType name="address">
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="Type" type="tns:addresstype"/>
                    <xsd:element minOccurs="0" name="Value" nillable="true" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="address" nillable="true" type="tns:address"/>
            <xsd:simpleType name="addresstype">
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Unspecified"/>
                    <xsd:enumeration value="Direct"/>
                    <xsd:enumeration value="Email"/>
                    <xsd:enumeration value="Fax"/>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:element name="addresstype" nillable="true" type="tns:addresstype"/>
            <xsd:complexType name="invalidinputfault">
                <xsd:complexContent mixed="false">
                    <xsd:extension base="q4:fault" xmlns:q4="http://api.relayhealth.com/2012/05/types">
                        <xsd:sequence/>
                    </xsd:extension>
                </xsd:complexContent>
            </xsd:complexType>
            <xsd:element name="invalidinputfault" nillable="true" type="tns:invalidinputfault"/>
            <xsd:complexType name="entitynotfoundfault">
                <xsd:complexContent mixed="false">
                    <xsd:extension base="q5:fault" xmlns:q5="http://api.relayhealth.com/2012/05/types">
                        <xsd:sequence/>
                    </xsd:extension>
                </xsd:complexContent>
            </xsd:complexType>
            <xsd:element name="entitynotfoundfault" nillable="true" type="tns:entitynotfoundfault"/>
            <xsd:complexType name="accessdeniedfault">
                <xsd:complexContent mixed="false">
                    <xsd:extension base="q6:fault" xmlns:q6="http://api.relayhealth.com/2012/05/types">
                        <xsd:sequence/>
                    </xsd:extension>
                </xsd:complexContent>
            </xsd:complexType>
            <xsd:element name="accessdeniedfault" nillable="true" type="tns:accessdeniedfault"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://api.relayhealth.com/2012/05/types" xmlns:tns="http://api.relayhealth.com/2012/05/types">
            <xsd:complexType name="fault">
                <xsd:sequence>
                    <xsd:element minOccurs="0" name="Message" nillable="true" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="fault" nillable="true" type="tns:fault"/>
        </xsd:schema>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://api.relayhealth.com/2012/06/messaging/types" xmlns:tns="http://api.relayhealth.com/2012/06/messaging/types">
            <xsd:simpleType name="dispositionType">
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Unspecified"/>
                    <xsd:enumeration value="Displayed"/>
                    <xsd:enumeration value="Dispatched"/>
                    <xsd:enumeration value="Processed"/>
                    <xsd:enumeration value="Deleted"/>
                    <xsd:enumeration value="Denied"/>
                    <xsd:enumeration value="Failed"/>
                </xsd:restriction>
            </xsd:simpleType>
            <xsd:element name="dispositionType" nillable="true" type="tns:dispositionType"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="messageDisposed_post_InputMessage">
        <wsdl:part element="tns:post" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="messageDisposed_post_OutputMessage">
        <wsdl:part element="tns:postResponse" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="messageDisposed_post_InvalidInputFaultFault_FaultMessage">
        <wsdl:part element="q7:invalidinputfault" name="detail" xmlns:q7="http://api.relayhealth.com/2012/05/messaging/types"/>
    </wsdl:message>
    <wsdl:message name="messageDisposed_post_EntityNotFoundFaultFault_FaultMessage">
        <wsdl:part element="q8:entitynotfoundfault" name="detail" xmlns:q8="http://api.relayhealth.com/2012/05/messaging/types"/>
    </wsdl:message>
    <wsdl:message name="messageDisposed_post_AccessDeniedFaultFault_FaultMessage">
        <wsdl:part element="q9:accessdeniedfault" name="detail" xmlns:q9="http://api.relayhealth.com/2012/05/messaging/types"/>
    </wsdl:message>
    <wsdl:message name="messageDisposed_post_FaultFault_FaultMessage">
        <wsdl:part element="q10:fault" name="detail" xmlns:q10="http://api.relayhealth.com/2012/05/types"/>
    </wsdl:message>
    <wsdl:portType name="messageDisposed">
        <wsdl:operation name="post">
            <wsdl:input message="tns:messageDisposed_post_InputMessage" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/post"/>
            <wsdl:output message="tns:messageDisposed_post_OutputMessage" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postResponse"/>
            <wsdl:fault message="tns:messageDisposed_post_InvalidInputFaultFault_FaultMessage" name="InvalidInputFaultFault" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postInvalidInputFaultFault"/>
            <wsdl:fault message="tns:messageDisposed_post_EntityNotFoundFaultFault_FaultMessage" name="EntityNotFoundFaultFault" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postEntityNotFoundFaultFault"/>
            <wsdl:fault message="tns:messageDisposed_post_AccessDeniedFaultFault_FaultMessage" name="AccessDeniedFaultFault" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postAccessDeniedFaultFault"/>
            <wsdl:fault message="tns:messageDisposed_post_FaultFault_FaultMessage" name="FaultFault" wsaw:Action="http://api.relayhealth.com/2012/06/messaging/messageDisposed/postFaultFault"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="soap11" type="tns:messageDisposed">
        <wsp:PolicyReference URI="#soap11_policy"/>
        <soap12:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="post">
            <soap12:operation soapAction="http://api.relayhealth.com/2012/06/messaging/messageDisposed/post" style="document"/>
            <wsdl:input>
                <soap12:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap12:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="InvalidInputFaultFault">
                <soap12:fault name="InvalidInputFaultFault" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="EntityNotFoundFaultFault">
                <soap12:fault name="EntityNotFoundFaultFault" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="AccessDeniedFaultFault">
                <soap12:fault name="AccessDeniedFaultFault" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="FaultFault">
                <soap12:fault name="FaultFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="messageDisposed">
        <wsdl:port binding="tns:soap11" name="soap11">
            <soap12:address location="https://api.integration.relayhealth.com/Messaging/MessageDisposed.svc"/>
            <wsa10:EndpointReference>
                <wsa10:Address>https://api.integration.relayhealth.com/Messaging/MessageDisposed.svc</wsa10:Address>
            </wsa10:EndpointReference>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>