//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMessagingApiClient.MessageServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messagebase", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.messagelistitem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.message))]
    public partial class messagebase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address[] CCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.dispositionType[] DispositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.patientidentifier[] PatientIdentifiersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.messagestate StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address[] ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address[] CC {
            get {
                return this.CCField;
            }
            set {
                if ((object.ReferenceEquals(this.CCField, value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.dispositionType[] Dispositions {
            get {
                return this.DispositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DispositionsField, value) != true)) {
                    this.DispositionsField = value;
                    this.RaisePropertyChanged("Dispositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.patientidentifier[] PatientIdentifiers {
            get {
                return this.PatientIdentifiersField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIdentifiersField, value) != true)) {
                    this.PatientIdentifiersField = value;
                    this.RaisePropertyChanged("PatientIdentifiers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate {
            get {
                return this.ReceivedDateField;
            }
            set {
                if ((this.ReceivedDateField.Equals(value) != true)) {
                    this.ReceivedDateField = value;
                    this.RaisePropertyChanged("ReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SentDate {
            get {
                return this.SentDateField;
            }
            set {
                if ((this.SentDateField.Equals(value) != true)) {
                    this.SentDateField = value;
                    this.RaisePropertyChanged("SentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.messagestate State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address[] To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="address", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.addresstype TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.addresstype Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messagelistitem", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class messagelistitem : SecureMessagingApiClient.MessageServiceReference.messagebase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.attachmentbase[] AttachmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.attachmentbase[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="message", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class message : SecureMessagingApiClient.MessageServiceReference.messagebase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.attachment[] AttachmentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.attachment[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dispositionType", Namespace="http://api.relayhealth.com/2012/06/messaging/types")]
    public enum dispositionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Displayed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dispatched = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Denied = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="patientidentifier", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class patientidentifier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssigningAuthorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssigningAuthority {
            get {
                return this.AssigningAuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.AssigningAuthorityField, value) != true)) {
                    this.AssigningAuthorityField = value;
                    this.RaisePropertyChanged("AssigningAuthority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Namespace {
            get {
                return this.NamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.NamespaceField, value) != true)) {
                    this.NamespaceField = value;
                    this.RaisePropertyChanged("Namespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messagestate", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    public enum messagestate : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationPassed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthorizationFailed = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InputValidationPassed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InputValidationFailed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VirusScanPassed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VirusScanFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submitted = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachment", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class attachment : SecureMessagingApiClient.MessageServiceReference.attachmentbase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="addresstype", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    public enum addresstype : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Direct = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachmentbase", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.attachment))]
    public partial class attachmentbase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentMimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentMimeType {
            get {
                return this.ContentMimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentMimeTypeField, value) != true)) {
                    this.ContentMimeTypeField = value;
                    this.RaisePropertyChanged("ContentMimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.accessdeniedfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.entitynotfoundfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidinputfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidoperationfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.virusinfectionfault))]
    public partial class fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class accessdeniedfault : SecureMessagingApiClient.MessageServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class entitynotfoundfault : SecureMessagingApiClient.MessageServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidinputfault : SecureMessagingApiClient.MessageServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidoperationfault : SecureMessagingApiClient.MessageServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
    [System.SerializableAttribute()]
    public partial class virusinfectionfault : SecureMessagingApiClient.MessageServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="messagerequest", Namespace="http://api.relayhealth.com/2012/08/messaging/types")]
    [System.SerializableAttribute()]
    public partial class messagerequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.attachmentrequest[] AttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address[] CCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address OnBehalfOfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SecureMessagingApiClient.MessageServiceReference.address[] ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.attachmentrequest[] Attachments {
            get {
                return this.AttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentsField, value) != true)) {
                    this.AttachmentsField = value;
                    this.RaisePropertyChanged("Attachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address[] CC {
            get {
                return this.CCField;
            }
            set {
                if ((object.ReferenceEquals(this.CCField, value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address OnBehalfOf {
            get {
                return this.OnBehalfOfField;
            }
            set {
                if ((object.ReferenceEquals(this.OnBehalfOfField, value) != true)) {
                    this.OnBehalfOfField = value;
                    this.RaisePropertyChanged("OnBehalfOf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SecureMessagingApiClient.MessageServiceReference.address[] To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachmentrequest", Namespace="http://api.relayhealth.com/2012/08/messaging/types")]
    [System.SerializableAttribute()]
    public partial class attachmentrequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentMimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentMimeType {
            get {
                return this.ContentMimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentMimeTypeField, value) != true)) {
                    this.ContentMimeTypeField = value;
                    this.RaisePropertyChanged("ContentMimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="message", Namespace="http://api.relayhealth.com/2012/05/messaging", ConfigurationName="MessageServiceReference.message1")]
    public interface message1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/message/get", ReplyAction="http://api.relayhealth.com/2012/05/messaging/message/getResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.virusinfectionfault), Action="http://api.relayhealth.com/2012/05/messaging/message/getVirusInfectionFaultFault", Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/message/getAccessDeniedFaultFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/message/getEntityNotFoundFaultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/message/getFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/message/getInvalidInputFaultFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        SecureMessagingApiClient.MessageServiceReference.message get(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/message/put", ReplyAction="http://api.relayhealth.com/2012/05/messaging/message/putResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidoperationfault), Action="http://api.relayhealth.com/2012/05/messaging/message/putInvalidOperationFaultFaul" +
            "t", Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/message/putFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/message/putAccessDeniedFaultFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/message/putInvalidInputFaultFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.virusinfectionfault), Action="http://api.relayhealth.com/2012/05/messaging/message/putVirusInfectionFaultFault", Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/message/putEntityNotFoundFaultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        bool put(SecureMessagingApiClient.MessageServiceReference.messagerequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/message/post", ReplyAction="http://api.relayhealth.com/2012/05/messaging/message/postResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.virusinfectionfault), Action="http://api.relayhealth.com/2012/05/messaging/message/postVirusInfectionFaultFault" +
            "", Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/message/postAccessDeniedFaultFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/message/postInvalidInputFaultFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/message/postFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        System.Guid post(SecureMessagingApiClient.MessageServiceReference.messagerequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/message/delete", ReplyAction="http://api.relayhealth.com/2012/05/messaging/message/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/message/deleteAccessDeniedFaultFault" +
            "", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/message/deleteInvalidInputFaultFault" +
            "", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/message/deleteEntityNotFoundFaultFau" +
            "lt", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.invalidoperationfault), Action="http://api.relayhealth.com/2012/05/messaging/message/deleteInvalidOperationFaultF" +
            "ault", Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/message/deleteFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        bool delete(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface message1Channel : SecureMessagingApiClient.MessageServiceReference.message1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class message1Client : System.ServiceModel.ClientBase<SecureMessagingApiClient.MessageServiceReference.message1>, SecureMessagingApiClient.MessageServiceReference.message1 {
        
        public message1Client() {
        }
        
        public message1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public message1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public message1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public message1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SecureMessagingApiClient.MessageServiceReference.message get(System.Guid id) {
            return base.Channel.get(id);
        }
        
        public bool put(SecureMessagingApiClient.MessageServiceReference.messagerequest request) {
            return base.Channel.put(request);
        }
        
        public System.Guid post(SecureMessagingApiClient.MessageServiceReference.messagerequest request) {
            return base.Channel.post(request);
        }
        
        public bool delete(System.Guid id) {
            return base.Channel.delete(id);
        }
    }
}
