//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMessagingApiClient.AttachmentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachmentbase", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.attachment))]
    public partial class attachmentbase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentMimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentMimeType {
            get {
                return this.ContentMimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentMimeTypeField, value) != true)) {
                    this.ContentMimeTypeField = value;
                    this.RaisePropertyChanged("ContentMimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                if ((this.FileSizeField.Equals(value) != true)) {
                    this.FileSizeField = value;
                    this.RaisePropertyChanged("FileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachment", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class attachment : SecureMessagingApiClient.AttachmentServiceReference.attachmentbase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.entitynotfoundfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.accessdeniedfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidoperationfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.virusinfectionfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidinputfault))]
    public partial class fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class entitynotfoundfault : SecureMessagingApiClient.AttachmentServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class accessdeniedfault : SecureMessagingApiClient.AttachmentServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidoperationfault : SecureMessagingApiClient.AttachmentServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
    [System.SerializableAttribute()]
    public partial class virusinfectionfault : SecureMessagingApiClient.AttachmentServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidinputfault : SecureMessagingApiClient.AttachmentServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="attachmentrequest", Namespace="http://api.relayhealth.com/2012/08/messaging/types")]
    [System.SerializableAttribute()]
    public partial class attachmentrequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentMimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncodingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentMimeType {
            get {
                return this.ContentMimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentMimeTypeField, value) != true)) {
                    this.ContentMimeTypeField = value;
                    this.RaisePropertyChanged("ContentMimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Encoding {
            get {
                return this.EncodingField;
            }
            set {
                if ((object.ReferenceEquals(this.EncodingField, value) != true)) {
                    this.EncodingField = value;
                    this.RaisePropertyChanged("Encoding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.relayhealth.com/2012/05/messaging", ConfigurationName="AttachmentServiceReference.messageAttachment")]
    public interface messageAttachment {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/get", ReplyAction="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getInvalidInputFau" +
            "ltFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.virusinfectionfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getVirusInfectionF" +
            "aultFault", Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getEntityNotFoundF" +
            "aultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/getAccessDeniedFau" +
            "ltFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        SecureMessagingApiClient.AttachmentServiceReference.attachment get(System.Guid messageId, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/post", ReplyAction="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.virusinfectionfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postVirusInfection" +
            "FaultFault", Name="virusinfectionfault", Namespace="http://api.relayhealth.com/2012/09/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postAccessDeniedFa" +
            "ultFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postInvalidInputFa" +
            "ultFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postEntityNotFound" +
            "FaultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidoperationfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/postInvalidOperati" +
            "onFaultFault", Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        System.Guid post(System.Guid messageId, SecureMessagingApiClient.AttachmentServiceReference.attachmentrequest attachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/delete", ReplyAction="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteEntityNotFou" +
            "ndFaultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidoperationfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteInvalidOpera" +
            "tionFaultFault", Name="invalidoperationfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteInvalidInput" +
            "FaultFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteAccessDenied" +
            "FaultFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.AttachmentServiceReference.fault), Action="http://api.relayhealth.com/2012/05/messaging/messageAttachment/deleteFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        bool delete(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface messageAttachmentChannel : SecureMessagingApiClient.AttachmentServiceReference.messageAttachment, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class messageAttachmentClient : System.ServiceModel.ClientBase<SecureMessagingApiClient.AttachmentServiceReference.messageAttachment>, SecureMessagingApiClient.AttachmentServiceReference.messageAttachment {
        
        public messageAttachmentClient() {
        }
        
        public messageAttachmentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public messageAttachmentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageAttachmentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageAttachmentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SecureMessagingApiClient.AttachmentServiceReference.attachment get(System.Guid messageId, System.Guid id) {
            return base.Channel.get(messageId, id);
        }
        
        public System.Guid post(System.Guid messageId, SecureMessagingApiClient.AttachmentServiceReference.attachmentrequest attachment) {
            return base.Channel.post(messageId, attachment);
        }
        
        public bool delete(System.Guid id) {
            return base.Channel.delete(id);
        }
    }
}
