//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureMessagingApiClient.MessageReceivedServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.entitynotfoundfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.accessdeniedfault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.invalidinputfault))]
    public partial class fault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class entitynotfoundfault : SecureMessagingApiClient.MessageReceivedServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class accessdeniedfault : SecureMessagingApiClient.MessageReceivedServiceReference.fault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
    [System.SerializableAttribute()]
    public partial class invalidinputfault : SecureMessagingApiClient.MessageReceivedServiceReference.fault {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.relayhealth.com/2012/06/messaging", ConfigurationName="MessageReceivedServiceReference.messageReceived")]
    public interface messageReceived {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.relayhealth.com/2012/06/messaging/messageReceived/post", ReplyAction="http://api.relayhealth.com/2012/06/messaging/messageReceived/postResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.invalidinputfault), Action="http://api.relayhealth.com/2012/06/messaging/messageReceived/postInvalidInputFaul" +
            "tFault", Name="invalidinputfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.entitynotfoundfault), Action="http://api.relayhealth.com/2012/06/messaging/messageReceived/postEntityNotFoundFa" +
            "ultFault", Name="entitynotfoundfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.fault), Action="http://api.relayhealth.com/2012/06/messaging/messageReceived/postFaultFault", Name="fault", Namespace="http://api.relayhealth.com/2012/05/types")]
        [System.ServiceModel.FaultContractAttribute(typeof(SecureMessagingApiClient.MessageReceivedServiceReference.accessdeniedfault), Action="http://api.relayhealth.com/2012/06/messaging/messageReceived/postAccessDeniedFaul" +
            "tFault", Name="accessdeniedfault", Namespace="http://api.relayhealth.com/2012/05/messaging/types")]
        bool post(System.Guid messageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface messageReceivedChannel : SecureMessagingApiClient.MessageReceivedServiceReference.messageReceived, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class messageReceivedClient : System.ServiceModel.ClientBase<SecureMessagingApiClient.MessageReceivedServiceReference.messageReceived>, SecureMessagingApiClient.MessageReceivedServiceReference.messageReceived {
        
        public messageReceivedClient() {
        }
        
        public messageReceivedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public messageReceivedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageReceivedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public messageReceivedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool post(System.Guid messageId) {
            return base.Channel.post(messageId);
        }
    }
}
